# Generated by Django 3.0 on 2026-02-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='actual_price',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
