# Generated by Django 3.0 on 2026-02-05 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0002_user_actual_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='actual_price',
        ),
        migrations.AddField(
            model_name='user',
            name='aactual_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
