# Generated by Django 3.0 on 2026-02-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapp', '0003_auto_20260206_0003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='aactual_price',
        ),
        migrations.AddField(
            model_name='user',
            name='actual_price',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='complaint',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='customer_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='imeino',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
